version: "2"
services:
  rtdb:
    image: oge/kdm-rtdb-vzdb:1.2.0
    ports:
      - "${rtdb_vzdb_port}:8040"
    networks:
      - oge_neworks
    environment:
      spring.application.name: kdm-rdp-rtdb-vzdb-${server_name}
      kdm.rtdb.host: vzdb-${vzdb_name} 
      kdm.rtdb.port: 22235
      kdm.rtdb.username: ${rtdb_username}
      kdm.rtdb.password: ${rtdb_password}
      kdm.rtdb.rule: ${rtdb_rule}
    volumes:
      - /home/oge/oge_logs/kdm-rdp-rtdb-vzdb-${rtdb_vzdb_port}/:/oge/log
      - /etc/localtime:/etc/localtime:ro
    container_name: kdm-rdp-rtdb-vzdb-${rtdb_vzdb_port}

networks:
  oge_neworks:
    external:
      name: test111
        